# # #
name: tml-smart-notifications-local

volumes:
    redis:

networks:
    redis:

# # #

services:
    # # # # # # # # # # # # # # # # # # # # #
    # # # # # # # # # # # # # # # # # # # # #

    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        networks:
            - redis
        volumes:
            - redis:/data
        ports:
            - 6379:6379

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: redis-commander
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 8081:8081
        networks:
            - redis
            
